# Generated by Django 5.2 on 2025-04-29 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_production_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('product_stock', models.CharField(max_length=100)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_img', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.AlterField(
            model_name='production_staff',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendence_status', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('duration_weeks', models.CharField(max_length=200)),
                ('loan_status', models.CharField(default='pending', max_length=10)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.CharField(max_length=200)),
                ('amount_paid', models.CharField(max_length=200)),
                ('paid_on', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(default='Pending', max_length=200)),
                ('loan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default=1, max_length=100)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_status', models.CharField(default='Booked', max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
