# Generated by Django 5.2 on 2025-04-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_alter_production_staff_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
