# Generated by Django 5.2 on 2025-04-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_loan_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='weekly_payment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
