# Generated by Django 5.2 on 2025-04-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_loan_weekly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pstatus',
            field=models.CharField(default='In Stock', max_length=100, null=True),
        ),
    ]
