# Generated by Django 5.2 on 2025-04-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_pstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.production_staff'),
        ),
    ]
