# Generated by Django 5.2 on 2025-04-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
