# Generated by Django 5.2 on 2025-05-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_booking_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='weekly_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_on',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='week_number',
        ),
    ]
