# Generated by Django 5.2 on 2025-05-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_loan_weekly_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_paid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='paid_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='week_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='weekly_payment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
