# Generated by Django 5.2 on 2025-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_loan_amount_paid_loan_paid_on_loan_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='paid_on',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='week_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='week_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
