# Generated by Django 5.2 on 2025-05-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_loan_amount_paid_remove_loan_paid_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
