# Generated by Django 4.2.1 on 2025-05-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_payment_due_date_loan_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
